rvm:
  - 2.6.1
  - 3.0
  - 3.2
before_install:
  - gem install bundler # uses newest bundler
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'
env:
  - "RAILS_VERSION=5.2.8.1"
  - "RAILS_VERSION=6.0.6.1"
  - "RAILS_VERSION=6.1.7.2"
  - "RAILS_VERSION=7.0.4.2"